spring:
  profiles:
    active: ${NODE_ENV:dev}
  datasource:
    jdbc-url: jdbc:mysql://localhost/test
    username: test
    password: test
    maximumPoolSize: 1
  data:
    mongodb:
      uri: mongodb://localhost/test
demo2:
  datasource:
    jdbc-url: jdbc:mysql://localhost/test
    username: test
    password: test
    maximumPoolSize: 1
